import type { Metadata } from "next";
import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Motive App",
  description: "Generated by Pabitra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <main className="">
          {/* <Toaster /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
